"""Configuration and constants for the career service"""
from pathlib import Path
import os

# Directory paths
# career-ml is now inside career-service (restructured for deployment)
SERVICE_DIR = Path(__file__).resolve().parent          # career-service/
ML_DIR = SERVICE_DIR / "career-ml"                     # career-service/career-ml/

# ── Data version toggle (set DATA_VERSION=v1 to revert) ─────────────────────
DATA_VERSION = os.getenv("DATA_VERSION", "v2").lower()

if DATA_VERSION == "v2":
    # V2 paths (expanded pipeline)
    ROLE_PROFILE_CSV       = ML_DIR / "data" / "processed" / "role_skill_profiles_v2.csv"
    CAREER_LADDERS_JSON    = ML_DIR / "data" / "processed" / "career_ladders_v2.json"
    ROLE_CLASSIFIER_PKL    = ML_DIR / "models" / "role_classifier_v2.pkl"
    JOB_SKILL_VECTORS_CSV  = ML_DIR / "data" / "processed" / "job_skill_vectors_v2.csv"
    SKILLS_CSV             = ML_DIR / "data" / "expanded" / "skills_v2.csv"
    ROLE_METADATA_JSON     = ML_DIR / "data" / "processed" / "role_metadata.json"
    SKILL_COLUMNS_PKL      = ML_DIR / "models" / "skill_columns_v2.pkl"
else:
    # V1 paths (legacy)
    ROLE_PROFILE_CSV       = ML_DIR / "skill_gap" / "role_skill_profiles.csv"
    CAREER_LADDERS_JSON    = ML_DIR / "career_path" / "career_ladders.json"
    ROLE_CLASSIFIER_PKL    = ML_DIR / "models" / "decision_tree_role_classifier.pkl"
    JOB_SKILL_VECTORS_CSV  = ML_DIR / "data" / "processed" / "job_skill_vectors.csv"
    SKILLS_CSV             = ML_DIR / "data" / "processed" / "skills.csv"
    ROLE_METADATA_JSON     = None
    SKILL_COLUMNS_PKL      = None

# Enhanced feature files (generated by career-ml/scripts/build_enhanced_features.py)
ROLE_ENHANCED_PROFILES_CSV = ML_DIR / "data" / "processed" / "role_enhanced_profiles.csv"
ENHANCED_FEATURE_COLUMNS_JSON = ML_DIR / "data" / "processed" / "enhanced_feature_columns.json"
JOBS_ENHANCED_FEATURES_CSV = ML_DIR / "data" / "processed" / "jobs_enhanced_features.csv"

# Gemini API Configuration (from explainability_engine.ipynb)
# NOTE: Do NOT hard-code API keys here. Configure them via environment variables
# or a local .env file that is NOT committed to Git.

# Optional: load environment variables from a local .env file if present
try:
	from dotenv import load_dotenv

	# Load .env from the career-service directory
	env_path = SERVICE_DIR / ".env"
	if env_path.exists():
		load_dotenv(env_path)
		print(f"[config] Loaded environment from {env_path}")
except ImportError:
	# python-dotenv not installed; environment must be set by the OS/shell
	pass

# Prefer GEMINI_API_KEY, but also support GOOGLE_API_KEY for compatibility with google-genai.
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY")

if GEMINI_API_KEY:
	# Ensure both env vars are set so google-genai can pick them up
	os.environ.setdefault("GEMINI_API_KEY", GEMINI_API_KEY)
	os.environ.setdefault("GOOGLE_API_KEY", GEMINI_API_KEY)
else:
	print(
		"[config] Warning: GEMINI_API_KEY/GOOGLE_API_KEY not set; "
		"Gemini explanations will use fallback templates only."
	)

# CORS settings
CORS_ORIGINS = ["http://localhost:3000", "http://127.0.0.1:3000"]
